name: "deploy-dev-eu-central-1"
on: 
  push:
    branches:
    - master
jobs:
  BuildAndPushToECR:
    name: "BuildAndPushToECR"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Aws Configure"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: "ECR login"
        uses: aws-actions/amazon-ecr-login@v1

      - name: "Build and Push"
        run: |
          docker build -t gateway-service:latest .
          docker tag gateway-service:latest 453613237449.dkr.ecr.eu-central-1.amazonaws.com/gateway-service-repository-dev:latest
          docker push 453613237449.dkr.ecr.eu-central-1.amazonaws.com/gateway-service-repository-dev:latest
  